package org.fonteditor.instructions;

public interface InstructionConstants {
  int INSTRUCTION_MASK = 0x00;
  int ERROR = INSTRUCTION_MASK | 0;
  int GLYPH_NUMBER = INSTRUCTION_MASK | 1;
  int GLYPH_NEXT = INSTRUCTION_MASK | 2;
  int STRAIGHT_LINE = INSTRUCTION_MASK | 3;
  int QUADRATIC_BEZIER = INSTRUCTION_MASK | 4;
  int CUBIC_BEZIER = INSTRUCTION_MASK | 5;
  int END_GLYPH = INSTRUCTION_MASK | 6;
  int END_FONT = INSTRUCTION_MASK | 7;
  int CLOSE_PATH = INSTRUCTION_MASK | 8;
  int OPEN_PATH = INSTRUCTION_MASK | 9;
  int MAX_NUMBER = 12;
}
